version: "3.9"
services:
  hub:
    image: umaprotocol/protocol:local
    build: ../../..
    env_file:
      - hub.env
      - bot-config.env
    ports:
      - "8081:8080"
  spoke:
    image: umaprotocol/protocol:local
    build: ../../..
    env_file: spoke.env
  scheduler:
    image: scheduler:local
    build: scheduler
    configs:
      - crontab
configs:
  crontab:
    file: scheduler/crontab
